spring.application.name=logi-route-project
spring.datasource.url=jdbc:postgresql://localhost:5432/logi_route
spring.datasource.username=logiroute
spring.datasource.password=logiroute
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.viacep.url=https://viacep.com.br