spring.application.name=logi-route-project
spring.datasource.url=${SPRING_DATASOURCE_JDBC_URL:${RENDER_JDBC_URL:${JDBC_DATABASE_URL:jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB:logiroute_db}}}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=America/Sao_Paulo
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

api.viacep.url=https://viacep.com.br